services:
  postgres:
    image: postgres:16
    container_name: my_postgres_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestJS_1
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nestJS_1']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data_1:
